/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockMultiVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvals"
      | "approve"
      | "atomCost"
      | "calculateAtomId"
      | "calculateTripleId"
      | "createAtoms"
      | "createAtomsCallCount"
      | "createTriples"
      | "createTriplesCallCount"
      | "deposit"
      | "depositBatch"
      | "depositBatchCallCount"
      | "depositCallCount"
      | "getAtomCost"
      | "getShares"
      | "getTriple"
      | "getTripleCost"
      | "isTermCreated"
      | "lastDepositAmount"
      | "lastDepositCurveId"
      | "lastDepositReceiver"
      | "lastDepositTermId"
      | "previewDeposit"
      | "setAtomCost"
      | "setShares"
      | "setTermCreated"
      | "setTripleCost"
      | "shares"
      | "termCreated"
      | "tripleCost"
      | "tripleObjects"
      | "triplePredicates"
      | "tripleSubjects"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approvals",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "atomCost", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateAtomId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTripleId",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAtoms",
    values: [BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createAtomsCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTriples",
    values: [BytesLike[], BytesLike[], BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createTriplesCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositBatch",
    values: [
      AddressLike,
      BytesLike[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositBatchCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAtomCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getShares",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTriple",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTripleCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTermCreated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDepositAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastDepositCurveId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastDepositReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastDepositTermId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewDeposit",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAtomCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setShares",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTermCreated",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTripleCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shares",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "termCreated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tripleCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tripleObjects",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triplePredicates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tripleSubjects",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "approvals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "atomCost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateAtomId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTripleId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAtoms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAtomsCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTriples",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTriplesCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositBatchCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAtomCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTriple", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTripleCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTermCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDepositAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDepositCurveId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDepositReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDepositTermId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAtomCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTermCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTripleCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "termCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tripleCost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tripleObjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triplePredicates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tripleSubjects",
    data: BytesLike
  ): Result;
}

export interface MockMultiVault extends BaseContract {
  connect(runner?: ContractRunner | null): MockMultiVault;
  waitForDeployment(): Promise<this>;

  interface: MockMultiVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvals: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [sender: AddressLike, approvalType: BigNumberish],
    [void],
    "nonpayable"
  >;

  atomCost: TypedContractMethod<[], [bigint], "view">;

  calculateAtomId: TypedContractMethod<[data: BytesLike], [string], "view">;

  calculateTripleId: TypedContractMethod<
    [subjectId: BytesLike, predicateId: BytesLike, objectId: BytesLike],
    [string],
    "view"
  >;

  createAtoms: TypedContractMethod<
    [data: BytesLike[], assets: BigNumberish[]],
    [string[]],
    "payable"
  >;

  createAtomsCallCount: TypedContractMethod<[], [bigint], "view">;

  createTriples: TypedContractMethod<
    [
      subjectIds: BytesLike[],
      predicateIds: BytesLike[],
      objectIds: BytesLike[],
      assets: BigNumberish[]
    ],
    [string[]],
    "payable"
  >;

  createTriplesCallCount: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [
      receiver: AddressLike,
      termId: BytesLike,
      curveId: BigNumberish,
      minShares: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  depositBatch: TypedContractMethod<
    [
      receiver: AddressLike,
      termIds: BytesLike[],
      curveIds: BigNumberish[],
      assets: BigNumberish[],
      minShares: BigNumberish[]
    ],
    [bigint[]],
    "payable"
  >;

  depositBatchCallCount: TypedContractMethod<[], [bigint], "view">;

  depositCallCount: TypedContractMethod<[], [bigint], "view">;

  getAtomCost: TypedContractMethod<[], [bigint], "view">;

  getShares: TypedContractMethod<
    [account: AddressLike, termId: BytesLike, curveId: BigNumberish],
    [bigint],
    "view"
  >;

  getTriple: TypedContractMethod<
    [tripleId: BytesLike],
    [
      [string, string, string] & {
        subjectId: string;
        predicateId: string;
        objectId: string;
      }
    ],
    "view"
  >;

  getTripleCost: TypedContractMethod<[], [bigint], "view">;

  isTermCreated: TypedContractMethod<[id: BytesLike], [boolean], "view">;

  lastDepositAmount: TypedContractMethod<[], [bigint], "view">;

  lastDepositCurveId: TypedContractMethod<[], [bigint], "view">;

  lastDepositReceiver: TypedContractMethod<[], [string], "view">;

  lastDepositTermId: TypedContractMethod<[], [string], "view">;

  previewDeposit: TypedContractMethod<
    [termId: BytesLike, curveId: BigNumberish, assets: BigNumberish],
    [[bigint, bigint]],
    "view"
  >;

  setAtomCost: TypedContractMethod<[_cost: BigNumberish], [void], "nonpayable">;

  setShares: TypedContractMethod<
    [
      account: AddressLike,
      termId: BytesLike,
      curveId: BigNumberish,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setTermCreated: TypedContractMethod<
    [termId: BytesLike, created: boolean],
    [void],
    "nonpayable"
  >;

  setTripleCost: TypedContractMethod<
    [_cost: BigNumberish],
    [void],
    "nonpayable"
  >;

  shares: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  termCreated: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  tripleCost: TypedContractMethod<[], [bigint], "view">;

  tripleObjects: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  triplePredicates: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  tripleSubjects: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [sender: AddressLike, approvalType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "atomCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateAtomId"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "calculateTripleId"
  ): TypedContractMethod<
    [subjectId: BytesLike, predicateId: BytesLike, objectId: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAtoms"
  ): TypedContractMethod<
    [data: BytesLike[], assets: BigNumberish[]],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createAtomsCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createTriples"
  ): TypedContractMethod<
    [
      subjectIds: BytesLike[],
      predicateIds: BytesLike[],
      objectIds: BytesLike[],
      assets: BigNumberish[]
    ],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTriplesCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      termId: BytesLike,
      curveId: BigNumberish,
      minShares: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositBatch"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      termIds: BytesLike[],
      curveIds: BigNumberish[],
      assets: BigNumberish[],
      minShares: BigNumberish[]
    ],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositBatchCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAtomCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getShares"
  ): TypedContractMethod<
    [account: AddressLike, termId: BytesLike, curveId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTriple"
  ): TypedContractMethod<
    [tripleId: BytesLike],
    [
      [string, string, string] & {
        subjectId: string;
        predicateId: string;
        objectId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTripleCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isTermCreated"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastDepositAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastDepositCurveId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastDepositReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastDepositTermId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewDeposit"
  ): TypedContractMethod<
    [termId: BytesLike, curveId: BigNumberish, assets: BigNumberish],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAtomCost"
  ): TypedContractMethod<[_cost: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setShares"
  ): TypedContractMethod<
    [
      account: AddressLike,
      termId: BytesLike,
      curveId: BigNumberish,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTermCreated"
  ): TypedContractMethod<
    [termId: BytesLike, created: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTripleCost"
  ): TypedContractMethod<[_cost: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shares"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "termCreated"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tripleCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tripleObjects"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "triplePredicates"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "tripleSubjects"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;

  filters: {};
}
