/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SofiaFeeProxyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "MAX_FEE_PERCENTAGE"
      | "calculateAtomId"
      | "calculateCreationFee"
      | "calculateDepositFee"
      | "calculateTripleId"
      | "createAtoms"
      | "createTriples"
      | "creationFixedFee"
      | "deposit"
      | "depositBatch"
      | "depositFixedFee"
      | "depositPercentageFee"
      | "ethMultiVault"
      | "feeRecipient"
      | "getAtomCost"
      | "getShares"
      | "getTotalCreationCost"
      | "getTotalDepositCost"
      | "getTriple"
      | "getTripleCost"
      | "isTermCreated"
      | "previewDeposit"
      | "setCreationFixedFee"
      | "setDepositFixedFee"
      | "setDepositPercentageFee"
      | "setFeeRecipient"
      | "setWhitelistedAdmin"
      | "whitelistedAdmins"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminWhitelistUpdated"
      | "CreationFixedFeeUpdated"
      | "DepositFixedFeeUpdated"
      | "DepositPercentageFeeUpdated"
      | "FeeRecipientUpdated"
      | "FeesCollected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAtomId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCreationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateDepositFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTripleId",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAtoms",
    values: [BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createTriples",
    values: [BytesLike[], BytesLike[], BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "creationFixedFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositBatch",
    values: [
      AddressLike,
      BytesLike[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFixedFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositPercentageFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ethMultiVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAtomCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getShares",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCreationCost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDepositCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTriple",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTripleCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTermCreated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "previewDeposit",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreationFixedFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositFixedFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositPercentageFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistedAdmin",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedAdmins",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateAtomId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateDepositFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTripleId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAtoms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTriples",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationFixedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFixedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPercentageFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethMultiVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAtomCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCreationCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDepositCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTriple", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTripleCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTermCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreationFixedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositFixedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositPercentageFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedAdmins",
    data: BytesLike
  ): Result;
}

export namespace AdminWhitelistUpdatedEvent {
  export type InputTuple = [admin: AddressLike, status: boolean];
  export type OutputTuple = [admin: string, status: boolean];
  export interface OutputObject {
    admin: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreationFixedFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositFixedFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositPercentageFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRecipientUpdatedEvent {
  export type InputTuple = [
    oldRecipient: AddressLike,
    newRecipient: AddressLike
  ];
  export type OutputTuple = [oldRecipient: string, newRecipient: string];
  export interface OutputObject {
    oldRecipient: string;
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesCollectedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    operation: string
  ];
  export type OutputTuple = [user: string, amount: bigint, operation: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    operation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SofiaFeeProxy extends BaseContract {
  connect(runner?: ContractRunner | null): SofiaFeeProxy;
  waitForDeployment(): Promise<this>;

  interface: SofiaFeeProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  calculateAtomId: TypedContractMethod<[data: BytesLike], [string], "view">;

  calculateCreationFee: TypedContractMethod<
    [count: BigNumberish],
    [bigint],
    "view"
  >;

  calculateDepositFee: TypedContractMethod<
    [depositAmount: BigNumberish],
    [bigint],
    "view"
  >;

  calculateTripleId: TypedContractMethod<
    [subjectId: BytesLike, predicateId: BytesLike, objectId: BytesLike],
    [string],
    "view"
  >;

  createAtoms: TypedContractMethod<
    [data: BytesLike[], assets: BigNumberish[]],
    [string[]],
    "payable"
  >;

  createTriples: TypedContractMethod<
    [
      subjectIds: BytesLike[],
      predicateIds: BytesLike[],
      objectIds: BytesLike[],
      assets: BigNumberish[]
    ],
    [string[]],
    "payable"
  >;

  creationFixedFee: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [
      receiver: AddressLike,
      termId: BytesLike,
      curveId: BigNumberish,
      minShares: BigNumberish,
      depositAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  depositBatch: TypedContractMethod<
    [
      receiver: AddressLike,
      termIds: BytesLike[],
      curveIds: BigNumberish[],
      assets: BigNumberish[],
      minShares: BigNumberish[]
    ],
    [bigint[]],
    "payable"
  >;

  depositFixedFee: TypedContractMethod<[], [bigint], "view">;

  depositPercentageFee: TypedContractMethod<[], [bigint], "view">;

  ethMultiVault: TypedContractMethod<[], [string], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getAtomCost: TypedContractMethod<[], [bigint], "view">;

  getShares: TypedContractMethod<
    [account: AddressLike, termId: BytesLike, curveId: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalCreationCost: TypedContractMethod<
    [count: BigNumberish, multiVaultCost: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalDepositCost: TypedContractMethod<
    [depositAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getTriple: TypedContractMethod<
    [tripleId: BytesLike],
    [[string, string, string]],
    "view"
  >;

  getTripleCost: TypedContractMethod<[], [bigint], "view">;

  isTermCreated: TypedContractMethod<[id: BytesLike], [boolean], "view">;

  previewDeposit: TypedContractMethod<
    [termId: BytesLike, curveId: BigNumberish, assets: BigNumberish],
    [[bigint, bigint]],
    "view"
  >;

  setCreationFixedFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDepositFixedFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDepositPercentageFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setWhitelistedAdmin: TypedContractMethod<
    [admin: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  whitelistedAdmins: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateAtomId"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "calculateCreationFee"
  ): TypedContractMethod<[count: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateDepositFee"
  ): TypedContractMethod<[depositAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateTripleId"
  ): TypedContractMethod<
    [subjectId: BytesLike, predicateId: BytesLike, objectId: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAtoms"
  ): TypedContractMethod<
    [data: BytesLike[], assets: BigNumberish[]],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTriples"
  ): TypedContractMethod<
    [
      subjectIds: BytesLike[],
      predicateIds: BytesLike[],
      objectIds: BytesLike[],
      assets: BigNumberish[]
    ],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creationFixedFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      termId: BytesLike,
      curveId: BigNumberish,
      minShares: BigNumberish,
      depositAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositBatch"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      termIds: BytesLike[],
      curveIds: BigNumberish[],
      assets: BigNumberish[],
      minShares: BigNumberish[]
    ],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositFixedFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositPercentageFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ethMultiVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAtomCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getShares"
  ): TypedContractMethod<
    [account: AddressLike, termId: BytesLike, curveId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalCreationCost"
  ): TypedContractMethod<
    [count: BigNumberish, multiVaultCost: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalDepositCost"
  ): TypedContractMethod<[depositAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTriple"
  ): TypedContractMethod<
    [tripleId: BytesLike],
    [[string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTripleCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isTermCreated"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "previewDeposit"
  ): TypedContractMethod<
    [termId: BytesLike, curveId: BigNumberish, assets: BigNumberish],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCreationFixedFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositFixedFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositPercentageFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWhitelistedAdmin"
  ): TypedContractMethod<
    [admin: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelistedAdmins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "AdminWhitelistUpdated"
  ): TypedContractEvent<
    AdminWhitelistUpdatedEvent.InputTuple,
    AdminWhitelistUpdatedEvent.OutputTuple,
    AdminWhitelistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CreationFixedFeeUpdated"
  ): TypedContractEvent<
    CreationFixedFeeUpdatedEvent.InputTuple,
    CreationFixedFeeUpdatedEvent.OutputTuple,
    CreationFixedFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositFixedFeeUpdated"
  ): TypedContractEvent<
    DepositFixedFeeUpdatedEvent.InputTuple,
    DepositFixedFeeUpdatedEvent.OutputTuple,
    DepositFixedFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositPercentageFeeUpdated"
  ): TypedContractEvent<
    DepositPercentageFeeUpdatedEvent.InputTuple,
    DepositPercentageFeeUpdatedEvent.OutputTuple,
    DepositPercentageFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeRecipientUpdated"
  ): TypedContractEvent<
    FeeRecipientUpdatedEvent.InputTuple,
    FeeRecipientUpdatedEvent.OutputTuple,
    FeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeesCollected"
  ): TypedContractEvent<
    FeesCollectedEvent.InputTuple,
    FeesCollectedEvent.OutputTuple,
    FeesCollectedEvent.OutputObject
  >;

  filters: {
    "AdminWhitelistUpdated(address,bool)": TypedContractEvent<
      AdminWhitelistUpdatedEvent.InputTuple,
      AdminWhitelistUpdatedEvent.OutputTuple,
      AdminWhitelistUpdatedEvent.OutputObject
    >;
    AdminWhitelistUpdated: TypedContractEvent<
      AdminWhitelistUpdatedEvent.InputTuple,
      AdminWhitelistUpdatedEvent.OutputTuple,
      AdminWhitelistUpdatedEvent.OutputObject
    >;

    "CreationFixedFeeUpdated(uint256,uint256)": TypedContractEvent<
      CreationFixedFeeUpdatedEvent.InputTuple,
      CreationFixedFeeUpdatedEvent.OutputTuple,
      CreationFixedFeeUpdatedEvent.OutputObject
    >;
    CreationFixedFeeUpdated: TypedContractEvent<
      CreationFixedFeeUpdatedEvent.InputTuple,
      CreationFixedFeeUpdatedEvent.OutputTuple,
      CreationFixedFeeUpdatedEvent.OutputObject
    >;

    "DepositFixedFeeUpdated(uint256,uint256)": TypedContractEvent<
      DepositFixedFeeUpdatedEvent.InputTuple,
      DepositFixedFeeUpdatedEvent.OutputTuple,
      DepositFixedFeeUpdatedEvent.OutputObject
    >;
    DepositFixedFeeUpdated: TypedContractEvent<
      DepositFixedFeeUpdatedEvent.InputTuple,
      DepositFixedFeeUpdatedEvent.OutputTuple,
      DepositFixedFeeUpdatedEvent.OutputObject
    >;

    "DepositPercentageFeeUpdated(uint256,uint256)": TypedContractEvent<
      DepositPercentageFeeUpdatedEvent.InputTuple,
      DepositPercentageFeeUpdatedEvent.OutputTuple,
      DepositPercentageFeeUpdatedEvent.OutputObject
    >;
    DepositPercentageFeeUpdated: TypedContractEvent<
      DepositPercentageFeeUpdatedEvent.InputTuple,
      DepositPercentageFeeUpdatedEvent.OutputTuple,
      DepositPercentageFeeUpdatedEvent.OutputObject
    >;

    "FeeRecipientUpdated(address,address)": TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;
    FeeRecipientUpdated: TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;

    "FeesCollected(address,uint256,string)": TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
    FeesCollected: TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
  };
}
