/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEthMultiVault,
  IEthMultiVaultInterface,
} from "../../interfaces/IEthMultiVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "calculateAtomId",
    outputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "subjectId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "predicateId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "objectId",
        type: "bytes32",
      },
    ],
    name: "calculateTripleId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
      {
        internalType: "uint256[]",
        name: "assets",
        type: "uint256[]",
      },
    ],
    name: "createAtoms",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "subjectIds",
        type: "bytes32[]",
      },
      {
        internalType: "bytes32[]",
        name: "predicateIds",
        type: "bytes32[]",
      },
      {
        internalType: "bytes32[]",
        name: "objectIds",
        type: "bytes32[]",
      },
      {
        internalType: "uint256[]",
        name: "assets",
        type: "uint256[]",
      },
    ],
    name: "createTriples",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "termId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "curveId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minShares",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "bytes32[]",
        name: "termIds",
        type: "bytes32[]",
      },
      {
        internalType: "uint256[]",
        name: "curveIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "assets",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "minShares",
        type: "uint256[]",
      },
    ],
    name: "depositBatch",
    outputs: [
      {
        internalType: "uint256[]",
        name: "shares",
        type: "uint256[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAtomCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "termId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "curveId",
        type: "uint256",
      },
    ],
    name: "getShares",
    outputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "tripleId",
        type: "bytes32",
      },
    ],
    name: "getTriple",
    outputs: [
      {
        internalType: "bytes32",
        name: "subjectId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "predicateId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "objectId",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTripleCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "isTermCreated",
    outputs: [
      {
        internalType: "bool",
        name: "exists",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "termId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "curveId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
    ],
    name: "previewDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "assetsAfterFees",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEthMultiVault__factory {
  static readonly abi = _abi;
  static createInterface(): IEthMultiVaultInterface {
    return new Interface(_abi) as IEthMultiVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEthMultiVault {
    return new Contract(address, _abi, runner) as unknown as IEthMultiVault;
  }
}
