/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IEthMultiVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateAtomId"
      | "calculateTripleId"
      | "createAtoms"
      | "createTriples"
      | "deposit"
      | "depositBatch"
      | "getAtomCost"
      | "getShares"
      | "getTriple"
      | "getTripleCost"
      | "isTermCreated"
      | "previewDeposit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateAtomId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTripleId",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAtoms",
    values: [BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createTriples",
    values: [BytesLike[], BytesLike[], BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositBatch",
    values: [
      AddressLike,
      BytesLike[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAtomCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getShares",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTriple",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTripleCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTermCreated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "previewDeposit",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateAtomId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTripleId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAtoms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTriples",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAtomCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTriple", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTripleCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTermCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewDeposit",
    data: BytesLike
  ): Result;
}

export interface IEthMultiVault extends BaseContract {
  connect(runner?: ContractRunner | null): IEthMultiVault;
  waitForDeployment(): Promise<this>;

  interface: IEthMultiVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateAtomId: TypedContractMethod<[data: BytesLike], [string], "view">;

  calculateTripleId: TypedContractMethod<
    [subjectId: BytesLike, predicateId: BytesLike, objectId: BytesLike],
    [string],
    "view"
  >;

  createAtoms: TypedContractMethod<
    [data: BytesLike[], assets: BigNumberish[]],
    [string[]],
    "payable"
  >;

  createTriples: TypedContractMethod<
    [
      subjectIds: BytesLike[],
      predicateIds: BytesLike[],
      objectIds: BytesLike[],
      assets: BigNumberish[]
    ],
    [string[]],
    "payable"
  >;

  deposit: TypedContractMethod<
    [
      receiver: AddressLike,
      termId: BytesLike,
      curveId: BigNumberish,
      minShares: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  depositBatch: TypedContractMethod<
    [
      receiver: AddressLike,
      termIds: BytesLike[],
      curveIds: BigNumberish[],
      assets: BigNumberish[],
      minShares: BigNumberish[]
    ],
    [bigint[]],
    "payable"
  >;

  getAtomCost: TypedContractMethod<[], [bigint], "view">;

  getShares: TypedContractMethod<
    [account: AddressLike, termId: BytesLike, curveId: BigNumberish],
    [bigint],
    "view"
  >;

  getTriple: TypedContractMethod<
    [tripleId: BytesLike],
    [
      [string, string, string] & {
        subjectId: string;
        predicateId: string;
        objectId: string;
      }
    ],
    "view"
  >;

  getTripleCost: TypedContractMethod<[], [bigint], "view">;

  isTermCreated: TypedContractMethod<[id: BytesLike], [boolean], "view">;

  previewDeposit: TypedContractMethod<
    [termId: BytesLike, curveId: BigNumberish, assets: BigNumberish],
    [[bigint, bigint] & { shares: bigint; assetsAfterFees: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateAtomId"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "calculateTripleId"
  ): TypedContractMethod<
    [subjectId: BytesLike, predicateId: BytesLike, objectId: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAtoms"
  ): TypedContractMethod<
    [data: BytesLike[], assets: BigNumberish[]],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTriples"
  ): TypedContractMethod<
    [
      subjectIds: BytesLike[],
      predicateIds: BytesLike[],
      objectIds: BytesLike[],
      assets: BigNumberish[]
    ],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      termId: BytesLike,
      curveId: BigNumberish,
      minShares: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositBatch"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      termIds: BytesLike[],
      curveIds: BigNumberish[],
      assets: BigNumberish[],
      minShares: BigNumberish[]
    ],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAtomCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getShares"
  ): TypedContractMethod<
    [account: AddressLike, termId: BytesLike, curveId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTriple"
  ): TypedContractMethod<
    [tripleId: BytesLike],
    [
      [string, string, string] & {
        subjectId: string;
        predicateId: string;
        objectId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTripleCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isTermCreated"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "previewDeposit"
  ): TypedContractMethod<
    [termId: BytesLike, curveId: BigNumberish, assets: BigNumberish],
    [[bigint, bigint] & { shares: bigint; assetsAfterFees: bigint }],
    "view"
  >;

  filters: {};
}
